[package]
name = "glow_tf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.11.2"
sdl2 = "0.35.1"
nalgebra-glm = "*"
